#!/usr/bin/env zsh

MINIMAL_FADE_COLOR=black

MINIMAL_ENABLE_VI_PROMPT=1
MINIMAL_SPACE_PROMPT=1

MINIMAL_PROMPT_SEP="|"

MINIMAL_BACKGROUND_JOB_SYM="♦"

MINIMAL_GIT_STASH_SYM='@'
MINIMAL_GIT_PUSH_SYM='↑'
MINIMAL_GIT_PULL_SYM='↓'
MINIMAL_GIT_UNSTAGE_SYM='+'
MINIMAL_GIT_STAGE_SYM='!'

MINIMAL_JAVA_SYM='☕️ '
MINIMAL_PY_SYM='🐍 '
MINIMAL_RB_SYM='RB: '
MINIMAL_GO_SYM='GO: '
MINIMAL_ELIXIR_SYM='EL:'
MINIMAL_AM_CRYSTAL_SYM='CR: '
MINIMAL_NODE_SYM='⬢ '
MINIMAL_PHP_SYM='PHP: '

MINIMAL_VERSION_REGEX="^VIRTUAL_ENV\|^PYENV\|^JENV\|^PATH"